version: '3.8'

services:
  # Frontend
  frontend:
    image: ${DOCKER_USERNAME}/flow-motion-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      api-gateway:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Backend Services
  api-gateway:
    image: ${DOCKER_USERNAME}/flow-motion-api-gateway:latest
    environment:
      - PORT=8080
      - NODE_ENV=production
      - USER_SERVICE_URL=http://user-service:4001
      - INVENTORY_SERVICE_URL=http://inventory-service:8000
      - ORDER_SERVICE_URL=http://order-service:4003
      - ROUTING_SERVICE_URL=http://routing-service:4004
      - GEO_SERVICE_URL=http://geolocation-service:4005
      - NOTIFY_SERVICE_URL=http://notification-service:4006
    ports:
      - "8080:8080"
    depends_on:
      user-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      routing-service:
        condition: service_healthy
      geolocation-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user-service:
    image: ${DOCKER_USERNAME}/flow-motion-user-service:latest
    environment:
      - PORT=4001
      - NODE_ENV=production
      - DATABASE_URL=${SUPABASE_DB_URL}
    ports:
      - "4001:4001"
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  inventory-service:
    image: ${DOCKER_USERNAME}/flow-motion-inventory-service:latest
    environment:
      - PORT=8000
      - DATABASE_URL=${SUPABASE_DB_URL}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    ports:
      - "8000:8000"
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  order-service:
    image: ${DOCKER_USERNAME}/flow-motion-order-service:latest
    environment:
      - PORT=4003
      - NODE_ENV=production
      - DATABASE_URL=${SUPABASE_DB_URL}
    ports:
      - "4003:4003"
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  routing-service:
    image: ${DOCKER_USERNAME}/flow-motion-routing-service:latest
    environment:
      - PORT=4004
      - NODE_ENV=production
    ports:
      - "4004:4004"
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 384M
        reservations:
          cpus: '0.25'
          memory: 192M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  geolocation-service:
    image: ${DOCKER_USERNAME}/flow-motion-geolocation-service:latest
    environment:
      - PORT=4005
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${SUPABASE_DB_URL}
    ports:
      - "4005:4005"
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 384M
        reservations:
          cpus: '0.25'
          memory: 192M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  notification-service:
    image: ${DOCKER_USERNAME}/flow-motion-notification-service:latest
    environment:
      - PORT=4006
      - NODE_ENV=production
    ports:
      - "4006:4006"
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  # Cache
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - logi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:

networks:
  logi-network:
    driver: bridge
    internal: true