global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:4001']
    scrape_interval: 10s
    metrics_path: '/api/metrics'

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:4003']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'routing-service'
    static_configs:
      - targets: ['host.docker.internal:4004']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'geolocation-service'
    static_configs:
      - targets: ['host.docker.internal:4005']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:4006']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:5432']
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']
    scrape_interval: 10s