apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logi-core
resources:
  - namespace.yaml
  - api-gateway.deployment.yaml
  - api-gateway.service.yaml
  - user-service.deployment.yaml
  - user-service.service.yaml
  - inventory-service.deployment.yaml
  - inventory-service.service.yaml
configMapGenerator:
  - name: api-gateway-config
    literals:
      - JWT_SECRET=dev-secret