apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/your-org/logi-core-user-service:dev
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"